# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQQIHa3rvVOF2CZnfoqwNbobo4LFXE2O
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

#path='/home/sid2018-3/Bureau/ProjetInterPromo/Interpromo2020/Interpromo2020/All Data/'
train=pd.read_excel('/content/ALL_DATA.xlsx', nrows=100)
train.shape

train.drop(["Type_Of_Traveller","Date_Visit","Date_Flown","Airport","Route","Category","Category_Detail","Date_Review"
            ,"Review","Type_Of_Lounge","Aircraft_Type","Seat"
            ,"Overall_Customer_Rating"], axis = 1, inplace = True)

train = pd.get_dummies(train, columns = ["Data_Source","Airline_Type","Region_Operation","Cabin_Class"
                                        ,"Seat_Type","Recommended"])

train_cr=train.drop(columns="Airline_Name")

train_cr.head()

for i in train_cr.columns:
  train_cr[i].fillna(train_cr[i].median(), inplace=True)
train_cr.head()

train_cr.to_csv('/content/train_cr.csv')

train_cr=pd.read_csv('/content/train_cr.csv', nrows=100)
train_cr.shape

train.index=train['Airline_Name']

#générer la matrice des liens
Z = linkage(train_cr,method='ward',metric='euclidean')

import matplotlib.pyplot as plt
plt.title("CAH")
dendrogram(Z,labels=train.index,orientation='left',color_threshold=0)
plt.show()

#matérialisation des 5 classes (hauteur t = 50)
from scipy.cluster.hierarchy import fcluster
plt.title('CAH avec matérialisation des 4 classes')
dendrogram(Z,labels=train.index,orientation='left',color_threshold=50)
plt.show()

#découpage à la hauteur t = 10 ==> identifiants de 5 groupes obtenus
from scipy.cluster.hierarchy import fcluster
groupes_cah = fcluster(Z,t=50,criterion='distance')
print(groupes_cah)

#index triés des groupes
import numpy as np
idg = np.argsort(groupes_cah)
#affichage des observations et leurs groupes
print(pd.DataFrame(train.index[idg],groupes_cah[idg]))

"""# sauvegarder les cluster"""

cluster=pd.DataFrame(train.index[idg],groupes_cah[idg])
cluster.to_csv('/content/cluster.csv')



